# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df7424d8f60a9731e20aa557008aa1de9d3a6857b1b679b1022005052149b6926145a9ae4382c3af247e821815532754895478c4a909af0359ef35994a77fb97

test:
  secret_key_base: 7cbd4edad445310419ae1c7cf9ab5efa1dc6dde177965d27247170c92446ce2779bfc46297c2bdf2ee10bf5523768a45b71c8a4da02e2292415ce03fbcea7969

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
